events {}

http {
  server {
    listen 80;

    location /api/service-1/ {
      proxy_pass http://lab2-service1:3000/;
    }

    location /api/service-2/ {
      proxy_pass http://lab2-service2:3001/;
    }
  }
}