pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Start network') {
            steps {
                sh 'docker network inspect lab2-net >/dev/null 2>&1 || docker network create lab2-net'
            }
        }

        stage('Deploy') {
            steps {
                dir('lab2/service_1') {
                    sh 'docker-compose -f docker-compose.yaml up -d --build'
                }
                dir('lab2/service_2') {
                    sh 'docker-compose -f docker-compose.yaml up -d --build'
                }
                dir('lab2/gateway') {
                    sh 'docker-compose -f docker-compose.yaml up -d --build'
                }
            }
        }
    }

    post {
        always {
            sh 'docker image prune -f'
        }
        success {
            echo 'Pipeline завершен успешно'
            sh 'docker ps'
        }
        failure {
            echo 'Pipeline завершен с ошибкой'
            sh 'docker ps'
        }
    }
}